apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: database
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: database
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: dbconnection
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: dbconnection
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: dbconnection
        image: registry.access.redhat.com/rhscl/mariadb-102-rhel7@sha256:44292f3eeaa3729372eee6fde9e1f07719172a1ca759f399619660bf1949192e
        imagePullPolicy: IfNotPresent
        name: database
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: db-pvc
