apiVersion: batch/v1
kind: Job
metadata:
  name: initial-db-load
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  suspend: false
  template:
    spec:
      containers:
      - image: registry.access.redhat.com/rhscl/mariadb-102-rhel7
        command:
        - bash
        - -c
        - 'mysql -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -h ${MYSQL_HOST} ${MYSQL_DATABASE} < /tmp/animals-dbdump'
        env:
        - name: MYSQL_HOST
          value: database
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: dbconnection
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: dbconnection
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: dbconnection
        imagePullPolicy: Always
        name: initial-db-load
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: load-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: db-initial-load
        name: load-volume
